### ISSUE TITLE
[tool] tag

### ISSUE THREAD

**Issue by GaugeK** [unixporn/upmo#47]
There should be a tag called [tool] which should be like OC, but for newly forked projects or projects that aren't yours but are interesting/useful.

**Comment by Foggalong** [comment]
Obviously not a mod anymore so can't comment as to the actual rules, but when [OC] was originally being written our forks were fine to use that and any other interesting things were to become under self post. The logic of the latter was to prevent "karma stealing" but because of how reddit has changed karma I guess that's no longer a working solution either.
